---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets-config
data:
  bucket-base-name: 'bucket-base-name_replace_me'
  bucket-source: 'https://s3.us-east-1.amazonaws.com/com.redhat.csds.guimou.xray-source'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
data:
  url-external: 'url-external_replace_me' # No trailing /
  url: 'http://rook-ceph-rgw-s3a.openshift-storage.svc.cluster.local' # No trailing /
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-host
data:
  url: xraylabdb
