apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: SUPERSET_ADMIN_PASSWORD
            value: admin
        repoRef:
          name: manifests-superset
          path: superset
      name: superset
    - kustomizeConfig:
        overlays:
          - storage-class
        parameters:
          - name: storage_class
            value: ocs-storagecluster-ceph-rbd
          - name: s3_endpoint_url
            value: s3.data.local
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        overlays:
          - storage-class
        parameters:
        - name: s3_endpoint_url
          value: s3.data.local
        - name: s3_credentials_secret
          value: secor-bucket
        - name: s3_bucket
          value: secor-bucket
        - name: s3_endpoint_url_prefix
          value: 'http://'
        - name: storage_class
          value: ocs-storagecluster-ceph-rbd
        repoRef:
          name: manifests-trino
          path: pattern2-smart-city/deploy/opendatahub/trino
      name: trino
  repos:
    - name: kf-manifests
      uri: 'https://github.com/kubeflow/manifests/tarball/v1.2-branch'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.11'
    - name: manifests-trino
      uri: 'https://github.com/red-hat-data-services/jumpstart-library/tarball/main'
    - name: manifests-superset
      uri: 'https://github.com/maulikjs/odh-manifests/tarball/e272300930ae424164e44172c74db29c060df1e8'
