kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "events-service:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/ubi8/python-38:latest"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/red-hat-data-services/jumpstart-library"
    contextDir: demo2-smart-city/source/SC_Event_Service
  triggers:
    - type: ConfigChange
  runPolicy: Serial
