apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: core-kafdrop
spec:
  selector:
    app: core-kafdrop
  replicas: 1
  template:
    metadata:
      labels:
        app: core-kafdrop
    spec:
      containers:
        - name: core-kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "core-kafka-kafka-bootstrap:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
---
apiVersion: v1
kind: Service
metadata:
  name: core-kafdrop
spec:
  selector:
    app: core-kafdrop
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: core-kafdrop
spec:
  subdomain: ""
  to:
    kind: Service
    name: core-kafdrop
    weight: 100
  port:
    targetPort: 9000
  wildcardPolicy: None
