kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: seed-database
  labels:
    app: seed-database
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "seed-database:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/ubi8/python-38:latest"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/red-hat-data-services/jumpstart-library"
    contextDir: demo2-smart-city/source/SC_Seed_Database
  triggers:
    - type: ConfigChange
  runPolicy: Serial
