apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: superset
  template:
    metadata:
      labels:
        app: superset
        deployment: superset
    spec:
      initContainers:
      - name: superset-init
        env:
        - name: SUPERSET_CONFIG_PATH
          value: /etc/superset/superset_config.py
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: $(superset_db_secret)
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: $(superset_db_secret)
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: $(superset_db_secret)
        envFrom:
          - secretRef:
              name: $(superset_secret)
        image: superset
        command: ['sh', '-c', "sleep 30; superset-init --username $SUPERSET_ADMIN_USER --firstname $SUPERSET_ADMIN_FNAME --lastname $SUPERSET_ADMIN_LNAME --email $SUPERSET_ADMIN_EMAIL --password $SUPERSET_ADMIN_PASSWORD"]
        volumeMounts:
          - mountPath: /etc/superset
            name: superset-config
      containers:
      - name: superset
        env:
        - name: SUPERSET_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SUPERSET_SECRET_KEY
              name: $(superset_secret)
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: $(superset_db_secret)
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: $(superset_db_secret)
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: $(superset_db_secret)
        - name: SUPERSET_CONFIG_PATH
          value: /etc/superset/superset_config.py
        image: superset
        ports:
          - containerPort: 8088
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/superset
            name: superset-config
        resources:
          requests:
            cpu: $(superset_cpu_requests)
            memory: $(superset_memory_requests)
          limits:
            cpu: $(superset_cpu_limits)
            memory: $(superset_memory_limits)
      serviceAccountName: superset
      volumes:
        - name: superset-config
          configMap:
            name: superset-config-py
            defaultMode: 420
